name: pi_metro
description: Criação de uma aplicação multiplataforma que permita o controle e acompanhamento da situação de cada equipamento de combate a incêndio. Inclui funcionalidades como rastreabilidade dos equipamentos, monitoramento da data de validade e localização, registro de manutenções, emissão de relatórios e programação de trocas.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  mysql_client: ^0.0.27
  http: ^1.2.0
  google_fonts: ^6.2.1
  email_validator: ^2.0.1
  uni_links: ^0.5.1
  shared_preferences: ^2.0.17 
  provider: ^6.0.4
  url_launcher: ^6.0.20  # Ou a versão mais recente
  webview_flutter: ^4.10.0
  intl: ^0.20.1
  printing: ^5.13.4
  pdf: ^3.11.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
  - lib/imgs/fundoHub.png
  - lib/imgs/telaCadastro.png
  - lib/imgs/trilhos.png
  - lib/imgs/logo.png
  - lib/imgs/telaLogin.png
  - lib/imgs/logo.jpeg
  - lib/imgs/Metro.jpeg
  - lib/imgs/pilar_metro_1.jpeg
  - lib/imgs/pilar_metro_2.jpeg
  - lib/imgs/default_profile.png
  - lib/imgs/logo_principal.jpeg

  uses-material-design: true
